name = "PathWeightSampling"
uuid = "e595aebf-dd45-48e4-a6c3-f40ecff26dc3"
version = "0.2.0"
authors = ["Manuel Reinhardt <manuel.rhdt@gmail.com>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[compat]
Accessors = "0.1"
DataFrames = "0.22, 1.0"
DiffEqBase = "6"
Distributions = "0.24, 0.25"
FastGaussQuadrature = "0.4.4, 1"
GZip = "0.6"
HDF5 = "0.15,0.16,0.17"
JSON = "0.21, 1"
LogExpFunctions = "0.3"
Parquet2 = "0.2"
ProgressMeter = "1.7.1"
RecipesBase = "1.0"
SciMLBase = "2"
StaticArrays = "0.12, 1.0"
Statistics = "1"
StatsBase = "0.33,0.34"
StatsFuns = "0.9, 1"
StochasticDiffEq = "6"
julia = "1.9"
